# -*- coding: utf-8 -*-
"""GLM_OCR_to_Excel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GwD6xsj8twYhWyTG4RpdRXIbUsKD02wa

# 🧾 GLM-OCR → Excel Pipeline
**Image of a table → GLM-OCR → HTML → Formatted Excel (.xlsx)**

### Setup
Before running: `Runtime → Change runtime type → T4 GPU`
"""

# ── CELL 1: Install dependencies ──────────────────────────────────────────
!pip install -q "transformers>=4.47.0" torch pillow openpyxl beautifulsoup4 markdown

# ── CELL 1: Install dependencies (install transformers from source — required for GLM-OCR) ──
!pip install -q git+https://github.com/huggingface/transformers.git
!pip install -q torch pillow openpyxl beautifulsoup4 markdown accelerate

# ── CELL 2: Load GLM-OCR model (downloads ~2GB, runs once) ────────────────
# ── CELL 2: Load GLM-OCR model ────────────────────────────────────────────
import torch
from transformers import AutoProcessor, AutoModelForImageTextToText

MODEL_PATH = "zai-org/GLM-OCR"

print("Loading processor...")
processor = AutoProcessor.from_pretrained(MODEL_PATH, trust_remote_code=True)

print("Loading model...")
model = AutoModelForImageTextToText.from_pretrained(
    MODEL_PATH,
    torch_dtype=torch.float16,   # float16 instead of bfloat16 — uses less VRAM on T4
    device_map="auto",
    trust_remote_code=True,
    low_cpu_mem_usage=True,      # loads weights incrementally
)
model.eval()   # disables dropout, saves VRAM

print(f"\n✅ Model loaded on: {next(model.parameters()).device}")
print(f"   VRAM used: {torch.cuda.memory_allocated() / 1e9:.2f} GB")

# ── CELL 3: GLM-OCR table extraction (exact logic from HF Space) ──────────
# ── CELL 3: GLM-OCR table extraction (memory-optimized) ──────────────────
import os
import gc
import tempfile
import torch
from PIL import Image, ImageOps

# Free up memory before inference
gc.collect()
torch.cuda.empty_cache()
torch.cuda.synchronize()

def extract_table_markdown(image_path: str) -> str:
    """Run GLM-OCR on an image and return Markdown table string."""
    image = Image.open(image_path)

    if image.mode in ("RGBA", "LA", "P"):
        image = image.convert("RGB")
    image = ImageOps.exif_transpose(image)

    # Resize if image is very large — reduces VRAM usage significantly
    max_dim = 1920
    w, h = image.size
    if max(w, h) > max_dim:
        scale = max_dim / max(w, h)
        image = image.resize((int(w * scale), int(h * scale)), Image.LANCZOS)
        print(f"  Resized image to {image.size} to save VRAM")

    tmp = tempfile.NamedTemporaryFile(delete=False, suffix=".png")
    image.save(tmp.name, "PNG")
    tmp.close()

    messages = [{
        "role": "user",
        "content": [
            {"type": "image", "url": tmp.name},
            {"type": "text",  "text": "Table Recognition:"},
        ],
    }]

    inputs = processor.apply_chat_template(
        messages,
        tokenize=True,
        add_generation_prompt=True,
        return_dict=True,
        return_tensors="pt",
    ).to(model.device)

    inputs.pop("token_type_ids", None)

    with torch.inference_mode():   # saves ~20% VRAM vs no_grad
        generated_ids = model.generate(
            **inputs,
            max_new_tokens=8192,
            use_cache=True,
        )

    output_text = processor.decode(
        generated_ids[0][inputs["input_ids"].shape[1]:],
        skip_special_tokens=True,
    )

    os.unlink(tmp.name)

    # Free memory after inference
    del inputs, generated_ids
    gc.collect()
    torch.cuda.empty_cache()

    return output_text.strip()

print("✅ GLM-OCR function ready")

# ── CELL 4: HTML → Excel converter ────────────────────────────────────────
from bs4 import BeautifulSoup
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

HEADER_FILL    = PatternFill('solid', start_color='1F4E79', end_color='1F4E79')
SUBHEADER_FILL = PatternFill('solid', start_color='2E75B6', end_color='2E75B6')
ALT_ROW_FILL   = PatternFill('solid', start_color='DEEAF1', end_color='DEEAF1')
WHITE_FILL     = PatternFill('solid', start_color='FFFFFF', end_color='FFFFFF')
HEADER_FONT    = Font(name='Arial', bold=True, color='FFFFFF', size=10)
SUBHEADER_FONT = Font(name='Arial', bold=True, color='FFFFFF', size=9)
DATA_FONT      = Font(name='Arial', size=9)
TOTAL_FONT     = Font(name='Arial', bold=True, color='FFFFFF', size=9)
THIN_SIDE      = Side(style='thin', color='BFBFBF')
THIN_BORDER    = Border(left=THIN_SIDE, right=THIN_SIDE, top=THIN_SIDE, bottom=THIN_SIDE)
CENTER_ALIGN   = Alignment(horizontal='center', vertical='center', wrap_text=True)
LEFT_ALIGN     = Alignment(horizontal='left',   vertical='center', wrap_text=True)

def parse_html_table(html_source):
    soup  = BeautifulSoup(html_source, 'html.parser')
    table = soup.find('table')
    if not table:
        raise ValueError('No <table> found in HTML.')
    def parse_group(tag):
        rows = []
        for tr in tag.find_all('tr', recursive=False):
            cells = []
            for cell in tr.find_all(['th', 'td'], recursive=False):
                cells.append({
                    'text':    cell.get_text(strip=True),
                    'rowspan': int(cell.get('rowspan', 1)),
                    'colspan': int(cell.get('colspan', 1)),
                })
            rows.append(cells)
        return rows
    thead = table.find('thead')
    tbody = table.find('tbody')
    header_rows = parse_group(thead) if thead else []
    data_rows   = [[c['text'] for c in row] for row in parse_group(tbody)] if tbody else []
    return header_rows, data_rows

def try_numeric(value):
    if value in ('-', '', None): return value
    try:
        f = float(value)
        return int(f) if f == int(f) else f
    except (ValueError, TypeError):
        return value

def write_headers(ws, header_rows):
    occupied = {}
    for row_idx, row in enumerate(header_rows):
        excel_row = row_idx + 1
        col = 1
        for ci in row:
            while occupied.get((excel_row, col)): col += 1
            rs, cs = ci['rowspan'], ci['colspan']
            fill = HEADER_FILL if (rs > 1 or row_idx == 0) else SUBHEADER_FILL
            font = HEADER_FONT if fill == HEADER_FILL else SUBHEADER_FONT
            if rs > 1 or cs > 1:
                ws.merge_cells(start_row=excel_row, end_row=excel_row+rs-1,
                               start_column=col, end_column=col+cs-1)
            c = ws.cell(row=excel_row, column=col, value=ci['text'])
            c.fill, c.font, c.alignment, c.border = fill, font, CENTER_ALIGN, THIN_BORDER
            for dr in range(rs):
                for dc in range(cs): occupied[(excel_row+dr, col+dc)] = True
            col += cs
    for (r, c) in occupied:
        cell = ws.cell(row=r, column=c)
        if not cell.value: cell.fill, cell.border = HEADER_FILL, THIN_BORDER
    return len(header_rows)

def write_data(ws, data_rows, start_row, num_cols):
    for i, row in enumerate(data_rows):
        r    = start_row + i
        fill = ALT_ROW_FILL if i % 2 == 0 else WHITE_FILL
        for j in range(num_cols):
            raw  = row[j] if j < len(row) else ''
            cell = ws.cell(row=r, column=j+1, value=try_numeric(raw))
            cell.fill, cell.font, cell.border = fill, DATA_FONT, THIN_BORDER
            cell.alignment = LEFT_ALIGN if j == 0 else CENTER_ALIGN

def write_totals(ws, data_rows, start_row, num_cols):
    total_row = start_row + len(data_rows)
    numeric_cols = set()
    for col_idx in range(num_cols):
        count = sum(1 for row in data_rows if col_idx < len(row)
                    and str(row[col_idx]).replace('.','').lstrip('-').isdigit())
        if count >= max(1, len(data_rows) * 0.3): numeric_cols.add(col_idx + 1)
    for col_idx in range(1, num_cols + 1):
        cl   = get_column_letter(col_idx)
        cell = ws.cell(row=total_row, column=col_idx)
        if col_idx == 1: cell.value = 'TOTAL'
        elif col_idx in numeric_cols:
            parts = [f'IFERROR({cl}{r}*1,0)' for r in range(start_row, total_row)]
            cell.value = '=' + '+'.join(parts)
        cell.fill, cell.font, cell.alignment, cell.border = SUBHEADER_FILL, TOTAL_FONT, CENTER_ALIGN, THIN_BORDER
    return total_row

def html_to_excel(html_source, output_path='output.xlsx', sheet_name='Sheet1'):
    header_rows, data_rows = parse_html_table(html_source)
    num_cols = max(sum(c['colspan'] for c in row) for row in header_rows) if header_rows \
               else max(len(r) for r in data_rows)
    wb = Workbook()
    ws = wb.active
    ws.title = sheet_name
    header_count = write_headers(ws, header_rows)
    data_start   = header_count + 1
    write_data(ws, data_rows, data_start, num_cols)
    total_row = write_totals(ws, data_rows, data_start, num_cols)
    for col_idx in range(1, num_cols + 1):
        cl = get_column_letter(col_idx)
        mx = max((len(str(c.value)) for c in ws[cl] if c.value), default=8)
        ws.column_dimensions[cl].width = max(8, min(30, mx + 4))
    for r in range(1, header_count + 1):
        ws.row_dimensions[r].height = 28 if r == 1 else 20
    for r in range(data_start, total_row + 1):
        ws.row_dimensions[r].height = 16
    ws.freeze_panes = ws.cell(row=data_start, column=2)
    wb.save(output_path)
    return output_path

print("✅ Excel converter ready")

# ── CELL 5: Upload your table image ───────────────────────────────────────
from google.colab import files

print("Upload your table image (JPG, PNG, WEBP)...")
uploaded   = files.upload()
image_path = list(uploaded.keys())[0]
print(f"\n✅ Uploaded: {image_path}")

# ── CELL 6: Run full pipeline: Image → OCR → HTML → Excel ────────────────
import markdown as md_lib
from pathlib import Path
from IPython.display import display, HTML, Markdown

output_filename = Path(image_path).stem + '.xlsx'

# Step 1 — GLM-OCR → Markdown
print("[1/3] Running GLM-OCR table recognition...")
md_table = extract_table_markdown(image_path)
print("\n── Raw Markdown output ──")
print(md_table)
display(Markdown(md_table))

# Step 2 — Markdown → HTML
print("\n[2/3] Converting Markdown → HTML...")
html_table = md_lib.markdown(md_table, extensions=["tables"])
display(HTML(html_table))

# Step 3 — HTML → Excel
print(f"\n[3/3] Generating Excel file: {output_filename}...")
html_to_excel(html_table, output_filename, sheet_name=Path(image_path).stem)
print(f"\n✅ Done! File saved as: {output_filename}")

# ── CELL 7: Download the Excel file ──────────────────────────────────────
from google.colab import files

files.download(output_filename)
print(f"📥 Downloading: {output_filename}")